mysite/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup, name='signup'),
]

mysite/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from pybo.views import index_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include(('pybo.urls', 'pybo'), namespace='pybo')),
    path('common/', include('common.urls')),
    path('', index_views.index, name='index'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/pybo/urls.py
from django.urls import path, re_path
from .views import index_views, question_views, answer_views, comment_views, ranking_views
from .views.index_views import CustomPasswordChangeForm

app_name = 'pybo'

urlpatterns = [
    # index_views.py
    path('', index_views.index, name='index'),
    path('<int:question_id>/', index_views.detail, name='detail'),
    path('accounts/', index_views.accounts, name='accounts'),
    path('accounts/edit_profile/', index_views.edit_profile, name='edit_profile'),
    path('accounts/change_password/', CustomPasswordChangeForm.as_view(), name='change_password'),

    path('users/<str:username>/', index_views.user_profile, name='user_profile'),

    # question_views.py
    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),
    path('question/vote/<int:question_id>/', question_views.question_vote, name='question_vote'),

    # answer_views.py
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),
    path('answer/vote/<int:answer_id>/', answer_views.answer_vote, name='answer_vote'),
    path('answer/accept/<int:answer_id>/', answer_views.answer_accept, name='answer_accept'),

    # comment_views.py
    path('comment/create/<int:answer_id>/', comment_views.comment_create, name='comment_create'),
    path('comment/modify/<int:comment_id>/', comment_views.comment_modify, name='comment_modify'),
    path('comment/delete/<int:comment_id>/', comment_views.comment_delete, name='comment_delete'),

    # Hashtag 관련 URL
    re_path(r'^hashtags/(?P<hashtag_slug>[\w가-힣]+)/$', index_views.hashtag_detail, name='hashtag_detail'),

    # 랭킹
    path('ranking/', ranking_views.user_ranking, name='user_ranking'),  
]

mysite/templates/form_errors.html
<!-- 필드 오류와 넌필드 오류 출력 -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <b>{{ field.label }}</b>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <b>{{ error }}</b>
    </div>
    {% endfor %}
</div>
{% endif %}

mysite/templates/help.html
<div class="alert alert-info" role="alert">
    <li>원하는 식의 양쪽을 '<b>$</b>'로 감싸 인라인 수식을 만들 수 있습니다.</li>
    <li>원하는 식의 양쪽을 '<b>$$</b>'로 감싸 수식 블록을 만들 수 있습니다.</li>
</div>

mysite/templates/index.html
{% load static %}
<!doctype html>
<html lang="ko">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <!-- font family -->
        <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@400;700&display=swap" rel="stylesheet">
        <!-- KaTeX -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css">
        <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.js"></script>
        <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/contrib/auto-render.min.js"></script>
        <script>
            document.addEventListener("DOMContentLoaded", function () {
                renderMathInElement(document.body, {
                delimiters: [
                    {left: "$$", right: "$$", display: true},
                    {left: "$", right: "$", display: false}
                ]
                });
            });
        </script>
        <!-- Bootstrap -->
        <script src="{% static 'bootstrap.min.js' %}"></script>
        <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
        <!-- SimpleMDE -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
        <script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
        <!-- <link rel="stylesheet" type="text/css" href="{% static 'simplemde.css' %}">
        <script src="{% static 'simplemde.js' %}"></script> -->
        <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
        <script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script> -->
        <!-- Fontawesome -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
        <script defer>
            document.addEventListener("DOMContentLoaded", function () {
                new SimpleMDE({
                    element: document.getElementById("markdown-editor"),
                    spellChecker: false
                });
            });
        </script>
        <!-- static -->
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
        <!-- title -->
        <title>Hello, pybo!</title>
    </head>

    <body class="d-flex flex-column min-vh-100">
        <!-- navbar -->
        {% include "navbar.html" %}
        <div class="d-flex flex-fill h-100">
            <!-- 엑기스 Start -->
            {% block content %}
            {% endblock content %}
            <!-- 엑기스 End -->
        </div>
        <footer class="bg-dark text-white text-center py-3">
            <div class="container">
                <p class="m-0">&copy; 2025 Pybo</p>
            </div>
        </footer>
        {% if messages %}
        <script>
            {% for message in messages %}
            alert("{{ message|escapejs }}");
            {% endfor %}
        </script>
        {% endif %}
    </body>
</html>

mysite/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'pybo:index' %}">Pybo</a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
                    {% else %}
                    <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                    {% endif %}
                </li>
                <li class="">
                    <a class="nav-link" href="{% url 'pybo:user_ranking' %}"><i class="fas fa-trophy mx-2"></i>랭킹</a>
                </li>
            </ul>
            {% if user.is_authenticated %}
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'pybo:user_profile' username=user.username %}"><i class="fas fa-user mx-2"></i>내 프로필</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'pybo:accounts' %}"><i class="fas fa-info-circle mx-2"></i>내 정보</a>
                </li>
            </ul>
            {% endif %}
        </div>
    </div>
</nav>