mysite/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from pybo.views import index_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include(('pybo.urls', 'pybo'), namespace='pybo')),
    path('common/', include('common.urls')),
    path('', index_views.index, name='index'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/pybo/urls.py
from django.urls import path, re_path
from .views import index_views, question_views, answer_views, comment_views, ranking_views
from .views.index_views import CustomPasswordChangeForm

app_name = 'pybo'

urlpatterns = [
    # index_views.py
    path('', index_views.index, name='index'),
    path('<int:question_id>/', index_views.detail, name='detail'),
    path('accounts/', index_views.accounts, name='accounts'),
    path('accounts/edit_profile/', index_views.edit_profile, name='edit_profile'),
    path('accounts/change_password/', CustomPasswordChangeForm.as_view(), name='change_password'),

    path('users/<str:username>/', index_views.user_profile, name='user_profile'),

    # question_views.py
    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),
    path('question/vote/<int:question_id>/', question_views.question_vote, name='question_vote'),

    # answer_views.py
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),
    path('answer/vote/<int:answer_id>/', answer_views.answer_vote, name='answer_vote'),
    path('answer/accept/<int:answer_id>/', answer_views.answer_accept, name='answer_accept'),

    # comment_views.py
    path('comment/create/<int:answer_id>/', comment_views.comment_create, name='comment_create'),
    path('comment/modify/<int:comment_id>/', comment_views.comment_modify, name='comment_modify'),
    path('comment/delete/<int:comment_id>/', comment_views.comment_delete, name='comment_delete'),

    # Hashtag 관련 URL
    re_path(r'^hashtags/(?P<hashtag_slug>[\w가-힣]+)/$', index_views.hashtag_detail, name='hashtag_detail'),

    # 랭킹
    path('ranking/', ranking_views.user_ranking, name='user_ranking'),  
]

mysite/pybo/models.py
# pybo/models.py

from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
from django.db.models.signals import post_save
from django.dispatch import receiver


class Question(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_question')
    subject = models.CharField(max_length=200)
    content = models.TextField()
    image = models.ImageField(upload_to="question_images/", null=True, blank=True)
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_question')
    is_anonymous = models.BooleanField(default=False)

    hashtags = models.ManyToManyField('Hashtag', blank=True, related_name='questions')

    def __str__(self):
        return self.subject

class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_answer')
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    image = models.ImageField(upload_to='answer_images/', blank=True, null=True)
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_answer')
    is_accepted = models.BooleanField(default=False)

class Comment(models.Model):
    answer = models.ForeignKey('Answer', on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField(auto_now_add=True)
    modify_date = models.DateTimeField(null=True, blank=True)

class Hashtag(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=50, unique=True, allow_unicode=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            from django.utils.text import slugify
            self.slug = slugify(self.name, allow_unicode=True)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    status = models.CharField(max_length=255, blank=True, default='')

    def __str__(self):
        return f"{self.user.username}의 프로필"


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)

mysite/pybo/views/answer_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from ..forms import AnswerForm
from ..models import Question, Answer

'''답변 등록'''
@login_required(login_url='common:login')
def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST, request.FILES)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('pybo:detail', question_id=question.id)
    else:
        form = AnswerForm()
    context = {'question': question, 'form': form}
    return render(request, 'pybo/question_detail.html', context)

'''답변 수정'''
@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '수정 권한이 없습니다.')
        return redirect('pybo:detail', question_id=answer.question.id)
    if request.method == "POST":
        form = AnswerForm(request.POST, request.FILES, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.modify_date = timezone.now()
            delete_checked = 'delete_image' in request.POST
            image_uploaded = request.FILES.get('image', None)
            if delete_checked:
                if answer.image:
                    answer.image.delete(save=False)
                    answer.image = None
            if image_uploaded:
                answer.image = image_uploaded
            answer.save()
            return redirect('pybo:detail', question_id=answer.question.id)
    else:
        form = AnswerForm(instance=answer)
    context = {'answer': answer, 'form': form}
    return render(request, 'pybo/answer_form.html', context)

'''답변 삭제'''
@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '삭제 권한이 없습니다.')
    else:
        answer.delete()
    return redirect('pybo:detail', question_id=answer.question.id)

'''답변 개추'''
@login_required(login_url='common:login')
def answer_vote(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user == answer.author:
        messages.error(request, '본인의 답변은 개추할 수 없습니다.')
    else:
        answer.voter.add(request.user)
    return redirect('pybo:detail', question_id=answer.question.id)

'''답변 채택'''
@login_required(login_url='common:login')
def answer_accept(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    question = answer.question
    # 질문자만 채택
    if request.user != question.author:
        messages.error(request, '채택할 수 없습니다.')
        return redirect('pybo:detail', question_id=question.id)
    # 채택된 답변 있는지 확인
    if question.answer_set.filter(is_accepted=True).exists():
        messages.error(request, '이미 채택된 답변이 있습니다.')
        return redirect('pybo:detail', question_id=question.id)
    # 채택
    answer.is_accepted = True
    answer.save()
    return redirect('pybo:detail', question_id=question.id)

mysite/pybo/views/comment_views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from ..models import Answer, Comment
from ..forms import CommentForm

@login_required(login_url='common:login')
def comment_create(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.answer = answer
            comment.create_date = timezone.now()
            comment.save()
    return redirect('pybo:detail', question_id=answer.question.id)

@login_required(login_url='common:login')
def comment_modify(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글 수정 권한이 없습니다.')
        return redirect('pybo:detail', question_id=comment.answer.question.id)

    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.modify_date = timezone.now()
            comment.save()
    return redirect('pybo:detail', question_id=comment.answer.question.id)

@login_required(login_url='common:login')
def comment_delete(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)

    if request.user != comment.author:
        messages.error(request, '댓글 삭제 권한이 없습니다.')
    else:
        comment.delete()

    return redirect('pybo:detail', question_id=comment.answer.question.id)

mysite/pybo/views/index_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from django.db.models import Q

from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from ..models import Question, Hashtag, UserProfile
from ..forms import QuestionForm
from ..forms import CustomPasswordChange

from django.contrib.auth.views import PasswordChangeView
from django import forms
from django.contrib.auth.models import User
from django.contrib import messages

def index(request):
    page = request.GET.get('page', '1')
    kw = request.GET.get('kw', '')  # 검색어
    question_list = Question.objects.order_by('-create_date')
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |  # 제목 검색
            Q(content__icontains=kw) |  # 내용 검색
            Q(answer__content__icontains=kw) |  # 답변 내용 검색
            Q(author__username__icontains=kw) |  # 질문 글쓴이 검색
            Q(answer__author__username__icontains=kw)  # 답변 글쓴이 검색
        ).distinct()
    paginator = Paginator(question_list, 10)  # 페이지당 10개
    page_obj = paginator.get_page(page)
    context = {'question_list': page_obj, 'page': page, 'kw': kw}
    return render(request, 'pybo/question_list.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    has_answered = question.answer_set.filter(author=request.user).exists() if request.user.is_authenticated else True
    accepted = question.answer_set.filter(is_accepted=True).first()
    context = {'question': question, 'has_answered': has_answered, 'accepted': accepted}
    return render(request, 'pybo/question_detail.html', context)

def question_list(request):
    questions = Question.objects.all().order_by('-create_date')
    hashtags = Hashtag.objects.all()
    return render(request, 'pybo/question_list.html', {'questions': questions, 'hashtags': hashtags})

def question_detail(request, pk):
    question = get_object_or_404(Question, pk=pk)
    return render(request, 'pybo/question_detail.html', {'question': question})

def hashtag_detail(request, hashtag_slug):
    hashtag = get_object_or_404(Hashtag, slug=hashtag_slug)
    questions = hashtag.questions.all().order_by('-create_date')
    context = {'hashtag': hashtag, 'questions': questions}
    return render(request, 'pybo/hashtag_list.html', context)

@login_required
def accounts(request):
    return render(request, 'pybo/mypage.html', {'user': request.user})

class EditProfileForm(forms.ModelForm):
    status = forms.CharField(
        max_length=255,
        required=False,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': '상태 메시지를 입력하세요...'})
    )
    class Meta:
        model = User
        fields = ['username', 'email']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
        }
    def __init__(self, *args, **kwargs):
        self.user = kwargs.get('instance')
        initial = kwargs.setdefault('initial', {})
        if self.user:
            try:
                initial['status'] = self.user.userprofile.status
            except UserProfile.DoesNotExist:
                pass
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control'})

    def save(self, commit=True):
        user = super().save(commit)
        profile, _ = UserProfile.objects.get_or_create(user=user)
        profile.status = self.cleaned_data['status']
        if commit:
            profile.save()
        return user

class CustomPasswordChangeForm(PasswordChangeView):
    form_class = CustomPasswordChange
    template_name = 'pybo/change_password.html'
    success_url = '/pybo/accounts/'
    def form_valid(self, form):
        messages.success(self.request, "비밀번호가 성공적으로 변경되었습니다.")
        return super().form_valid(form)

@login_required
def edit_profile(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, "프로필이 성공적으로 변경되었습니다.")
            return redirect('pybo:accounts')
    else:
        form = EditProfileForm(instance=request.user)
    return render(request, 'pybo/edit_profile.html', {'form': form})

def user_profile(request, username):
    user_obj = get_object_or_404(User, username=username)
    try:
        profile = user_obj.userprofile
    except UserProfile.DoesNotExist:
        profile = None
    return render(request, 'pybo/user_profile.html', {
        'user_obj': user_obj,
        'profile': profile,
    })

mysite/pybo/views/ranking_views.py
from django.contrib.auth.models import User
from django.db.models import Count, Q
from django.shortcuts import render

def user_ranking(request):
    ranking = User.objects.annotate(
        accepted_count=Count('author_answer', filter=Q(author_answer__is_accepted=True))
    ).order_by('-accepted_count')

    return render(request, 'pybo/user_ranking.html', {'ranking': ranking})

mysite/templates/pybo/answer_form.html
{% extends 'index.html' %}
{% block content %}
<!-- 답변 수정-->
<div class="container my-3">
    {% include 'help.html' %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="content" class="form-label">답변 내용</label>
            <textarea class="form-control" name="content" id="markdown-editor" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <div class="mb-3">
            <label for="image" class="mb-1">사진 첨부하기</label>
            <input type="file" name="image" id="image" class="form-control" accept="image/*">
        </div>
        {% if form.instance.image %}
            <div id="image-preview" class="position-relative mb-3">
                <img src="{{ form.instance.image.url }}" style="max-width: 200px; border-radius: 4px;">
                <input type="checkbox" name="delete_image" id="delete_image" class="d-none">
                <label for="delete_image" class="btn-close position-absolute top-0 end-0 m-2" title="삭제"></label>
            </div>
        {% endif %}
        <div class="text-end">
            <button type="submit" class="btn btn-primary">답변 등록하기</button>
        </div>
    </form>
</div>

<script>
  document.addEventListener("DOMContentLoaded", function () {
    const deleteCheckbox = document.getElementById("delete_image");
    const imagePreview = document.getElementById("image-preview");

    if (deleteCheckbox && imagePreview) {
      deleteCheckbox.addEventListener("change", function () {
        if (this.checked) {
          imagePreview.style.display = "none";
        } else {
          imagePreview.style.display = "block";
        }
      });
    }
  });
</script>

{% endblock %}

mysite/templates/pybo/delete_account.html
{% extends "index.html" %}
{% block content %}
<div class="container bg-white px-4 py-5" style="max-width: 600px;">
  <h2 class="fw-bold mb-4">계정 삭제</h2>
  <form method="post">
    {% csrf_token %}
    {% include "form_errors.html" %}

    <div class="mb-3">
      <label for="{{ form.password.id_for_label }}" class="form-label">비밀번호</label>
      {{ form.password }}
    </div>

    <div class="d-flex gap-2">
      <button type="submit" class="btn btn-danger">계정 삭제</button>
      <a href="{% url 'pybo:edit_profile' %}" class="btn btn-secondary">취소</a>
    </div>
  </form>
</div>
{% endblock content %}

mysite/templates/pybo/edit_profile.html
{% extends "index.html" %}
{% block content %}
<div class="container-fluid bg-white px-4 py-5">
  <div class="mx-auto" style="max-width: 640px;">

    <h2 class="fw-bold mb-4">프로필 수정</h2>

    <form method="post" novalidate>
      {% csrf_token %}
      {% include "form_errors.html" %}

      <div class="mb-3">
        <label for="{{ form.username.id_for_label }}" class="form-label">사용자 이름</label>
        {{ form.username }}
      </div>

      <div class="mb-3">
        <label for="{{ form.email.id_for_label }}" class="form-label">이메일</label>
        {{ form.email }}
      </div>

      <div class="mb-3">
        <label for="id_status" class="form-label">상태 메시지 (최대 255자)</label>
        {{ form.status }}
      </div>

      <div class="d-flex gap-2">
        <button type="submit" class="btn btn-primary">저장</button>
        <a href="{% url 'pybo:accounts' %}" class="btn btn-secondary">취소</a>
      </div>
    </form>
  </div>
</div>
{% endblock content %}

mysite/templates/pybo/mypage.html
{% extends 'index.html' %}
{% block content %}

<div class="container py-5" style="max-width: 600px;">
    <!-- 프로필 상단 -->
    <h2 class="fw-bold mb-3">{{ user.username }}님의 정보</h2>
    {% if user.userprofile.status %}
    <p><i class="fas fa-comment-alt mx-2"></i>{{ user.userprofile.status }}</p>
    {% endif %}
    <hr>
    <p><i class="fas fa-envelope mx-2"></i>{{ user.email }}</p>
    <p><i class="fas fa-calendar-alt mx-2"></i>{{ user.date_joined|date:"Y년 m월 d일" }}~</p>

    <!-- 계정 관리 버튼 -->
    <div class="d-flex gap-2 mb-4">
        <a href="{% url 'pybo:edit_profile' %}" class="btn btn-outline-primary">정보 수정</a>
        <a href="{% url 'pybo:change_password' %}" class="btn btn-outline-secondary">비밀번호 변경</a>
    </div>
</div>
{% endblock content %}

mysite/templates/pybo/question_detail.html
{% extends 'index.html' %}
{% load pybo_filter %}

{% block content %}
<div class="container my-3">
    <!-- 질문 -->
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="bg-light text-black p-3 text-start mb-3 w-100">
                {% if question.is_anonymous %}
                <div class="fw-bold mb-2 fs-5">익명 질문</div>
                {% else %}
                <div class="fw-bold mb-2 fs-5">
                    <a href="{% url 'pybo:user_profile' username=question.author.username %}">
                    {{ question.author.username }}</a>님의 질문
                </div>
                {% endif %}
                <div class="fs-6">등록: {{ question.create_date }}</div>
                {% if question.modify_date %}
                <div class="fs-6">수정: {{ question.modify_date }}</div>
                {% endif %}
            </div>
            <div class="card-text mb-3 px-3">
                <div class="card-text">{{ question.content|mark }}</div>
                {% if question.image %}
                <img src="{{ question.image.url }}" class="img-fluid">
                {% endif %}
                {% if question.hashtags %}
                    <div class="mt-3">
                    {% for hashtag in question.hashtags.all %}
                    <a href="{% url 'pybo:hashtag_detail' hashtag.slug %}" class="badge bg-info text-dark me-1">
                    #{{ hashtag.name }}
                    </a>
                    {% endfor %}
                    </div>
                {% endif %}
            </div>
            <a href="{% url 'pybo:question_vote' question.id  %}"
                class="recommend btn btn-sm btn-outline-secondary"> 개추
                <span class="badge rounded-pill bg-success">{{question.voter.count}}</span>
            </a>
            {% if request.user == question.author %}
            <a href="{% url 'pybo:question_modify' question.id  %}" 
                class="btn btn-sm btn-outline-secondary">수정</a>
            <a href="{% url 'pybo:question_delete' question.id  %}" class="delete btn btn-sm btn-outline-secondary">삭제</a>
            {% endif %}
        </div>
    </div>
    <!-- 답변 -->
    <!-- 채택 -->
    <h4 class="border-bottom my-3 py-2 fw-bold">답변 {{ question.answer_set.count }}개</h4>
    {% for answer in question.answer_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <!-- 채택 -->
            {% if answer.is_accepted %}
                <div class="fs-4 mb-3 text-success fw-bold">✅ 채택된 답변</div>
            {% endif %}
            <div class="bg-light text-black p-3 text-start mb-3 w-100">
                <div class="fw-bold mb-2 fs-5">
                    <a href="{% url 'pybo:user_profile' username=answer.author.username %}">
                    {{ answer.author.username }}</a>님의 답변
                </div>
                <div class="fs-6">등록: {{ answer.create_date }}</div>
                {% if answer.modify_date %}
                <div class="fs-6">수정: {{ answer.modify_date }}</div>
                {% endif %}
            </div>
            <div class="card-text mb-3 px-3">
                <div class="card-text">{{ answer.content|mark }}</div>
                {% if answer.image %}
                <img src="{{ answer.image.url }}" class="img-fluid">
                {% endif %}
            </div>
            <!-- 채택 버튼 -->
            {% if request.user == question.author and not accepted %}
                <form method="post" action="{% url 'pybo:answer_accept' answer.id %}">
                {% csrf_token %}
                <div class="text-end"><button type="submit" class="btn btn-sm btn-outline-success p-3">답변 채택하기</button></div>
                </form>
            {% endif %}
            <!-- 댓글 목록 -->
            <ul class="mt-3 small text-muted">
            {% for comment in answer.comments.all %}
                <li>
                <span>{{ comment.author.username }} ({{ comment.create_date|date:"Y.m.d H:i" }}){% if comment.modify_date %} ({{ comment.modify_date|date:"Y.m.d H:i" }} 수정됨){% endif %}<br>{{ comment.content }}</span>

                {% if request.user == comment.author %}
                    <!-- 수정 버튼 -->
                    <div class="text-end">
                        <a href="javascript:void(0);" onclick="toggleEditForm({{ comment.id }})">✏️</a>
                        <a href="{% url 'pybo:comment_delete' comment.id %}" class="ms-2">🗑️</a>
                    </div>

                    <!-- 인라인 수정 폼 (처음엔 숨김) -->
                    <form method="post"
                        action="{% url 'pybo:comment_modify' comment.id %}"
                        id="edit-form-{{ comment.id }}"
                        style="display: none; margin-top: 0.5rem;">
                    {% csrf_token %}
                    <div class="input-group">
                        <input type="text" name="content" class="form-control form-control-sm"
                            value="{{ comment.content }}">
                        <button type="submit" class="btn btn-sm btn-outline-primary">저장</button>
                    </div>
                    </form>
                {% endif %}
                </li>
            {% endfor %}
            </ul>

            <!-- 댓글 작성 폼 -->
            <form method="post" action="{% url 'pybo:comment_create' answer.id %}" class="mb-3">
                {% csrf_token %}
                <div class="input-group mt-2">
                <textarea name="content" class="form-control" rows="5" placeholder="댓글을 작성하세요..."></textarea>
                <button class="btn btn-outline-secondary ms-3" type="submit">등록</button>
                </div>
            </form>
            <div>
                <a href="javascript:void(0)" data-uri="{% url 'pybo:answer_vote' answer.id  %}"
                   class="recommend btn btn-sm btn-outline-secondary"> 개추
                <span class="badge rounded-pill bg-success">{{answer.voter.count}}</span>
                </a>
                {% if request.user == answer.author %}
                <a href="{% url 'pybo:answer_modify' answer.id  %}" 
                class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="#" class="delete btn btn-sm btn-outline-secondary "
                   data-uri="{% url 'pybo:answer_delete' answer.id  %}">삭제</a>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}

    <!-- 답변 등록 -->
    <div {% if has_answered or accepted or request.user == question.author %}style="display: none;"{% endif %}>
        <h4 class="border-bottom my-3 py-2 fw-bold">답변 등록하기</h4>
        {% include 'help.html' %}
        <form action="{% url 'pybo:answer_create' question.id %}" method="post" class="my-3" enctype="multipart/form-data">
            {% csrf_token %}
            <!-- 오류표시 Start -->
            {% if form.errors %}
            <div class="alert alert-danger" role="alert">
                {% for field in form %}
                {% if field.errors %}
                <div>
                    <b>{{ field.label }}</b>
                    {{ field.errors }}
                </div>
                {% endif %}
                {% endfor %}
            </div>
            {% endif %}
            <!-- 오류표시 End -->
            <div class="mb-3">
                <textarea {% if not user.is_authenticated %}disabled{% endif %} name="content" id="markdown-editor" class="form-control" rows="10" placeholder="내용을 입력하세요..."></textarea>
            </div>
            <div class="mb-3">
                <label for="image">사진 첨부</label>
                <input {% if not user.is_authenticated %}disabled{% endif %} type="file" name="image" id="image" class="form-control" accept="image/*">
            </div>
            {% if form.instance.image %}
            <div class="position-relative d-inline-block mb-3">
                <img src="{{ form.instance.image.url }}" style="max-width: 200px; border-radius: 8px; box-shadow: 0 0 8px rgba(0,0,0,0.1);">
                <input type="checkbox" name="delete_image" id="delete_image" class="d-none">
                <label for="delete_image" class="btn-close position-absolute top-0 end-0 m-1" title="이미지 삭제" style="background-color: rgba(255,255,255,0.8); padding: .5rem;">
                </label>
            </div>
            {% endif %}
            <div class="text-end">
                <button type="submit" class="btn btn-primary">답변 등록하기</button>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

{% block script %}
<script>
    const delete_elements = document.getElementsByClassName("delete");
    Array.from(delete_elements).forEach(function(element) {
        element.addEventListener('click', function() {
            if(confirm("정말 삭제하시겠습니까?")) {
                location.href = this.dataset.uri;
            };
        });
    });
    const recommend_elements = document.getElementsByClassName("recommend");
    Array.from(recommend_elements).forEach(function(element) {
        element.addEventListener('click', function() {
            if(confirm("정말 개추하시겠습니까?")) {
                location.href = this.dataset.uri;
            };
        });
    });
</script>
<script>
  function toggleEditForm(commentId) {
    const form = document.getElementById("edit-form-" + commentId);
    if (form.style.display === "none") {
      form.style.display = "block";
    } else {
      form.style.display = "none";
    }
  }
</script>
{% endblock script %}

mysite/templates/pybo/user_ranking.html
{% extends 'index.html' %}
{% block content %}
<div class="container my-5">
    <h2 class="mb-4 fw-bold">🏆 채택 랭킹 TOP 10</h2>
    <ol class="list-group list-group-numbered">
        {% for user in ranking %}
        <li class="list-group-item d-flex justify-content-between align-items-center">
            <a href="{% url 'pybo:user_profile' username=user.username %}">{{ user.username }}</a>
            <span class="badge bg-success rounded-pill">{{ user.accepted_count }}회 채택</span>
        </li>
        {% endfor %}
    </ol>
</div>
{% endblock content %}